// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoVwSSi4iEIvoVYd4QdUP7nh5xWfn40f8',
    appId: '1:781806715058:web:9586432ae93d393cb8c9ab',
    messagingSenderId: '781806715058',
    projectId: 'shaheen-star-app',
    authDomain: 'shaheen-star-app.firebaseapp.com',
    storageBucket: 'shaheen-star-app.firebasestorage.app',
    measurementId: 'G-LG45B506WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXit5gBx0P_ddcoTnssQ6j_LaDsJqgjrc',
    appId: '1:828536498276:android:2e02dcfcc71a0996c35771',
    messagingSenderId: '828536498276',
    projectId: 'shaheen-star-690f3',
    storageBucket: 'shaheen-star-690f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8BnG39AgOCAzJX_F_LNZqYoIw9htmdHw',
    appId: '1:828536498276:ios:bd99f99426a93304c35771',
    messagingSenderId: '828536498276',
    projectId: 'shaheen-star-690f3',
    storageBucket: 'shaheen-star-690f3.firebasestorage.app',
    androidClientId: '828536498276-ad500uk1v30a44l15cr4lverjl5g2eei.apps.googleusercontent.com',
    iosClientId: '828536498276-l1b99mk1996fub1iegdnkd1pq293g78t.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaheenStarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd025lsvjS3wYD3GrAeZxNQvMeLKigOeI',
    appId: '1:781806715058:ios:5b32b9145a2e7d21b8c9ab',
    messagingSenderId: '781806715058',
    projectId: 'shaheen-star-app',
    storageBucket: 'shaheen-star-app.firebasestorage.app',
    iosClientId: '781806715058-a68alh16m42na9ov4p8vfo8sv8jvqd2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaheenStarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoVwSSi4iEIvoVYd4QdUP7nh5xWfn40f8',
    appId: '1:781806715058:web:2ae8430f05f3019db8c9ab',
    messagingSenderId: '781806715058',
    projectId: 'shaheen-star-app',
    authDomain: 'shaheen-star-app.firebaseapp.com',
    storageBucket: 'shaheen-star-app.firebasestorage.app',
    measurementId: 'G-4XDQFVXZT5',
  );
}